### ISSUE TITLE
Error when reproducing your code: ValueError: cannot reshape array of size 294912 into shape (16,49152)

### ISSUE THREAD

**Issue by plzampieri** [rdcolema/tensorflow-image-classification#24]
Hello, 
I'm trying to reproduce your code to my own images. In order to make it work, had to change some method to the compatible version, i.e.  tf.compat.v1.train.AdamOptimizer
Even if, I'm having problems in the function 'print_validation_accuracy()'
do you have any idea on how to fix it? See the error below:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-48-2b682d29d7b3> in <module>()
----> 1 print_validation_accuracy()
      2 #esta com erros
<ipython-input-46-cfb7087f526b> in print_validation_accuracy(show_example_errors, show_confusion_matrix)
     20 
     21         # Get the images from the test-set between index i and j.
---> 22         images = data.valid.images[i:j, :].reshape(batch_size, img_size_flat)
     23 
     24         # Get the associated labels.
ValueError: cannot reshape array of size 294912 into shape (16,49152)

**Comment by rdcolema** [comment]
Hey @plzampieri, I haven't updated this code in a long time so could be out of date, but based on the error I believe the issue is that  the code is trying to reshape the data into `(batch_size, img_size_flat)` which in your case is (16, 49152). These two numbers multiplied together should equal the total size of your data, but they don't in the case since the total size of your data is 294912  instead of 786432. 

`img_size_flat` is computed as the number of channels in your image, which is 3 for color images or 1 for black and white, multiplied by the height and width of the image. If your image isn't square, you'll probably have to modify the `img_size_flat` declaration since that assumes a square image. 

If that doesn't work, you could try playing around with the batch size too. 

And if you find anything outdated or hard to reproduce, feel free to open a pull request and I'd be happy to include.

**Comment by plzampieri** [comment]
Hey, @rdcolema 
First of all, thank you for replying it back to me. Very kind of you.
I guess my problem is because of batch_size as you mentioned. When I changed for 10, it worked. I have 320 images for this, so it can't be divided by 16, however by 10 it can :-) 

When I print this line when it's running you can see this result below: (Take a look)
Added this line to see what's was happening:
        print ("batch_size = ", batch_size, " img_size_flat=",img_size_flat, " shape=",  
                  data.valid.images[i:j, :].shape ) - see the results below:

See that in last line, the shape was (6,128,128,3)
batch_size =  16  img_size_flat= 49152  shape= (16, 128, 128, 3)
batch_size =  16  img_size_flat= 49152  shape= (16, 128, 128, 3)

batch_size =  16  img_size_flat= 49152  shape= (6, 128, 128, 3)
That's why I can reshape it. 

BTW: Do you have more code on Image Classification besides this one? This is looks very good and I'm trying to learning from it.

Thank you and have a great week.
Paulo.

**Comment by rdcolema** [comment]
Nice, glad you got it working. 

I worked on a few other projects that involved image classification -- they're all a bit old too but might still be useful:

- https://github.com/rdcolema/pytorch-image-classification
- https://github.com/rdcolema/keras-image-classification
- https://github.com/rdcolema/nc-fish-classification
